JuDFTteam/masci-tools

masci_tools/io/parsers/fleur/fleur_schema/fleur_schema_parser_functions.py
Some optimizations in `fleur_schema_parser_functions`. The runtime is dominated by the xpath construction functions and the actual xpath calls (since they are mostly relative and very general)
This pull request adds caching for these functions and cuts the runtime by a factor 3
=> Cache xpath results

masci_tools/io/cif2inp_ase.py
Independent utility script to convert `cif/poscar/vasp/xyz` file formats to input for the `inpgen` code
Usage: `python cif2inp_ase.py <filename.cif>`
=> Utility to convert CIF file to inpgen input

docs/source/module_guide/code.rst, masci_tools/io/fleurxmlmodifier.py, masci_tools/io/io_nmmpmat.py, masci_tools/tests/test_fleurxmlmodifier.py, masci_tools/tests/test_xml_setters_nmmpmat.py, masci_tools/util/xml/xml_setters_nmmpmat.py
Move low-level formatting/setting and rotating of n_mmp_mat entries to separate module so that they can be easily used without a xml to create a custom n_mmp_mat file
Support for:
- Rotating the density matrix block
- Converting block from n_mmp_mat to 7x7 complex numpy array
- Specifying a density matrix via complete numpy array, diagonal elements or occupations of atomic orbitals (separate, if wished there could also be combined setting routine)
=> Expose n_mmp_mat low level manipulation without inp.xml

masci_tools/io/common_functions.py, masci_tools/tests/test_common_functions.py, masci_tools/tests/test_schema_dict_util.py, masci_tools/tests/test_xml_common_functions.py, masci_tools/util/schema_dict_util.py, masci_tools/util/xml/common_functions.py
This PR expands the capabilities of the schema_dict_util functions, when handling nodes, that are not on the root of the XML file. Previously the tag of the node was taken as a constraint and `eval_xpath` converted the absolute xpath from the schema dictionary to a relative xpath starting from that tag.
Unfortunately this works only on one level. Consider the following examples for extracting the Hubbard U from a ldaU tag
```python
#Read in xmltree and load schema_dict before
from masci_tools.util.schema_dict_util import eval_simple_xpath, evaluate_attribute
species_elems = eval_simple_xpath(xmltree, schema_dict, 'species', list_return=True)
for species in species_elems:
print(evaluate_attribute(species, schema_dict, 'U', contains='ldaU', constants=constants))
```
```python
#Read in …
```
=> Improve schema_dict_util functions for for relative xpaths

.bumpversion.cfg, masci_tools/__init__.py, masci_tools/io/parsers/fleur/fleur_inpxml_parser.py, masci_tools/io/parsers/fleur/fleur_outxml_parser.py, masci_tools/io/parsers/fleur/fleur_schema/add_fleur_schema.py, masci_tools/io/parsers/fleur/fleur_schema/inpschema_todict.py, masci_tools/io/parsers/fleur/fleur_schema/outschema_todict.py, masci_tools/tests/test_xml_common_functions.py, masci_tools/tests/test_xml_setters_names.py, masci_tools/util/xml/common_functions.py, masci_tools/util/xml/converters.py, masci_tools/util/xml/xml_getters.py, masci_tools/util/xml/xml_setters_basic.py, masci_tools/util/xml/xml_setters_xpaths.py, pyproject.toml, setup.py
This Release contains:
- various bugfixes for xml modifying functions
- A special case for `theta`, `phi` and `ef_shift` attributes of `forceTheorem` tags, since they are not correctly typed in the Inputschema
- Introduced function to split a xmltree back up into the included subtrees and the main tree with `xi: include` tags
- `clear_xml` now returns a set of the tags, that were included
=> Release 0.4.5

docs/source/module_guide/tools.rst, masci_tools/io/fleurxmlmodifier.py, masci_tools/util/schema_dict_util.py, masci_tools/util/typing.py, masci_tools/util/xml/common_functions.py, masci_tools/util/xml/xml_setters_basic.py, masci_tools/util/xml/xml_setters_names.py, masci_tools/util/xml/xml_setters_nmmpmat.py, masci_tools/util/xml/xml_setters_xpaths.py, masci_tools/util/xml/xpathbuilder.py, tests/test_fleurxmlmodifier.py, tests/xml/test_schema_dict_util.py, tests/xml/test_xml_common_functions.py, tests/xml/test_xml_getters.py, tests/xml/test_xml_setter_signatures/test_xml_setter_signatures.yml, tests/xml/test_xml_setters_names.py, tests/xml/test_xpathbuilder.py
See #93
This PR provides a class to construct complex xpath expressions with predicates from simple xpaths via a dictionary inspired by the filters in AiiDAs QueryBuilder.
This functionality is then forwarded by providing the option of passing these filters to schema_dict_util and xml_setters functions
One bonus feature is that the programmatic construction allows usage of xpath variables making the functions much more robust and safe
TODO:
=> XPathBuilder

CHANGELOG.md, docs/source/devel_guide/fleur_parser.rst, masci_tools/io/parsers/fleur/default_parse_tasks.py, masci_tools/io/parsers/fleur/outxml_conversions.py, masci_tools/util/parse_tasks.py, tests/parsers/test_parse_tasks.py
The parsing tasks pre-date the xml getters and at some points try to replicate behaviour,
which is very well defined and constructed in the xml_getters (e.g. reading cell and atoms data).
In the next release of Fleur there are some changes that would need to be taken into account to keep the film_relax_info
and bulk_relax_info tasks working, which is not worth it.
Instead we allow parse_type to be `xmlGetter` and give an argument `name` for the function
=> Allow referencing xml_getter functions in outxml parsing tasks

.pre-commit-config.yaml, CHANGELOG.md, masci_tools/io/parsers/fleur/default_parse_tasks.py, masci_tools/io/parsers/fleur/outxml_conversions.py, masci_tools/util/parse_tasks.py, masci_tools/util/parse_utils.py, tests/parsers/test_fleur_outxml_parser/test_outxml_broken_firstiter.yml
Inspired by the same mechanism for transformations in `HDF5Reader`. Since the old way provided no way of giving arguments the conversion functions are quite static and need to be made custom for all types. See [ase-fleur](https://github.com/JuDFTteam/ase-fleur/blob/develop/ase_fleur/io.py) for an example of this problem. Maybe at some point we can even unify the transformations in hdf5 and the ones for the xml parser
=> Move to namedtuples for conversion function definitions in `outxml_parser`

CHANGELOG.md, masci_tools/io/parsers/fleur_schema/schema_dict.py, masci_tools/util/xml/common_functions.py, tests/xml/test_xml_common_functions.py
previously the string was just checked for the containing tag
this hass a number of drawbacks including if the tag is in a Xpath
predicate or another part of the xpath contains the tag name to search
A function contains_tag is introduced to solve these problems. This
strips out the predicates and creates the explicit list of contained
tags.
=> Make detection whether a xpath contains a tag more robust

CHANGELOG.md, masci_tools/io/fleurxmlmodifier.py, masci_tools/util/xml/xml_setters_basic.py, masci_tools/util/xml/xml_setters_names.py, masci_tools/util/xml/xml_setters_xpaths.py, tests/io/test_fleurxmlmodifier.py, tests/xml/test_xml_setter_signatures/test_xml_setter_signatures.yml
Cleanup signatures of XML setter signatures. Main changes are
1. `attributedict`/`change_dict` -> `changes`
2. `attributename`/`attribv` -> `name`/`value`
3. Fixed bug , where the signatures of `set_text`/`set_first_text`
contained `attributename` and `attribv`
These changes with the exception of the bugfix in `set_text` are deprecated when used via the `FleurXMLModifier`
=> Cleanup XML setter arguments

.github/workflows/cd.yml, .github/workflows/ci.yml, CHANGELOG.md
I noticed this project uses the pytest-mpl HTML summary, however the CI is only saving the HTML file as an artifact and not the whole results directory. This means that when you download the artifact and open it, the images are not shown. This PR fixes this, and is similar to [this](https://github.com/SciTools/cartopy/blob/22cdafca511744143c5b673598a1889f169c1e3d/.github/workflows/ci-testing.yml#L90).
You may want to also include the `${{ matrix.python-version }}` in the artifact name and path so each job doesn't write the same artifact.
=> Fix pytest-mpl artifact upload

CHANGELOG.md, masci_tools/util/xml/common_functions.py, masci_tools/util/xml/xml_setters_basic.py, masci_tools/util/xml/xml_setters_names.py, masci_tools/util/xml/xml_setters_xpaths.py, tests/xml/test_xml_setters_basic.py, tests/xml/test_xml_setters_names.py, tests/xml/test_xml_setters_xpaths.py
This is a preparation to allow these kinds of functions in aiida-fleur.
The calcfunction of the FleurinpModifier can't accept the elements
directly since they go through a json serialization. The idea would be
to convert elements into strings and then reconstructing them once inside
the XML setters in masci-tools
=> Allow XML setters to accept strings for `etree.fromstring` in place of `etree._Element`

CHANGELOG.md, masci_tools/io/fleurxmlmodifier.py, tests/io/test_fleurxmlmodifier.py
This property produces output compatible with the `fromList` classmethod (which is importantly the method used to read the `inpxml_changes` input)
This is a small step towards making the construction of `inpxml_changes` inputs in `aiida-fleur`
easier
=> Add `task_list` property to FleurXMLModifier

docs/source/devel_guide/fleur_parser.rst, docs/source/devel_guide/plot_data.rst, docs/source/devel_guide/plotting.rst, docs/source/index.rst, docs/source/user_guide/fleur_parser.rst, docs/source/user_guide/fleur_plots.rst, docs/source/user_guide/fleurxmlmodifier.rst, docs/source/user_guide/hdf5_parser.rst, docs/source/user_guide/plotting.rst
Shorten references in user guide by using `.. currentmodule`. Also introduce explicit linebreaks to make the docs easier to edit. THe last should have no effect on the formatting in the actual webpage
=> Cleanup references in docs

.github/workflows/cd.yml, .github/workflows/ci.yml, .readthedocs.yml, CHANGELOG.md, docs/source/conf.py, masci_tools/io/parsers/fleur_schema/fleur_schema_parser_functions.py, masci_tools/util/xml/converters.py, masci_tools/util/xml/xpathbuilder.py, pyproject.toml
The docs are now build on python 3.10. The reason for this are some
unsupported things related to the typehints. This switch allows the
simplification of the requirements and dropping the sphinx-toolbox
requirement
=> Update docs build

.pre-commit-config.yaml, CHANGELOG.md, docs/source/module_guide/tools.rst, masci_tools/io/fleurxmlmodifier.py, masci_tools/util/xml/xml_setters_basic.py, masci_tools/util/xml/xml_setters_names.py, utils/write_fleurxmlmodifier_docstrings.py
Changes done to the docstrings of XML setter methods in `FleurXMLModifier` will be overwritten by this hook.
The source of the docstrings is now only the XML setter functions
=> Autogenerate docstrings in `FleurXMLModifier` via pre-commit hook

.pre-commit-config.yaml, CHANGELOG.md, masci_tools/__init__.py, masci_tools/util/ipython.py, pyproject.toml
Pulled out of #157 
To use add `%load_ext masci_tools`
For now this includes rendering lxml trees with syntax highlighting
and HTML
Other ideas:
Example from the above mentioned pull request docs
=> Add module for tools to use in an ipython/jupyter notebook

CHANGELOG.md, masci_tools/io/fleur_xml.py, masci_tools/tools/fleur_inpxml_converter.py, masci_tools/util/schema_dict_util.py, masci_tools/util/xml/common_functions.py, masci_tools/util/xml/converters.py, masci_tools/util/xml/xml_setters_basic.py, masci_tools/util/xml/xml_setters_names.py, masci_tools/util/xml/xml_setters_nmmpmat.py, masci_tools/util/xml/xml_setters_xpaths.py, tests/xml/test_xml_common_functions.py
Added
- `eval_xpath_all` returns all results
- `eval_xpath_one` returns one result and makes sure there is only one
- `eval_xpath_first` returns the first result
All three accept the argument `expected_type`, which is used to check the results of the XPath evaluation
=> Add runtime type checking of XPath evaluation routines

CHANGELOG.md, masci_tools/util/schema_dict_util.py, masci_tools/util/xml/common_functions.py, masci_tools/util/xml/converters.py, masci_tools/util/xml/xml_setters_xpaths.py, tests/xml/test_xml_converters.py, tests/xml/test_xml_setters_xpaths.py
Triggering example
```python
from masci_tools.io.fleurxmlmodifier import FleurXMLModifier
fm = FleurXMLModifier()
fm.set_inpchanges({'forcealpha': None})
fm.modify_xmlfile('inp.xml')
```
=> Make sure that values in `convert_to_xml` are not `None`

CHANGELOG.md, masci_tools/cmdline/commands/fleur_schema.py
schema files at once from the git
Switched around some order of checks in the `masci-tools fleur-schema add`
to avoid unnecessary checks when `--from-git` flag is given
=> Add `masci-tools fleur-schema pull <branch>` to update XML Schemas

CHANGELOG.md, masci_tools/util/xml/common_functions.py, tests/files/fleur/test_clear_multiple_comments.xml, tests/xml/test_xml_common_functions.py
This would previously fail if there were multiple comments after or before the root XML element
=> Bugfix in `clear_xml` for comment removal

CHANGELOG.md, masci_tools/util/schema_dict_util.py, tests/xml/test_schema_dict_util.py
this would not detect when the relax.xml include was already present and would enter a second xi:include tag breaking the inp.xml
=> Fix condition in `ensure_relaxation_xinclude`

masci_tools/io/fleurxmlmodifier.py, tests/io/test_fleurxmlmodifier.py
In the validation step switch out the file version for the one expected from the used fallback schema
=> `FleurXMLModifier`: explicitly support dev versions with warnings
